### ISSUE TITLE
Setting 204 on the client side?

### ISSUE THREAD

**Issue by nathanscovil** [SinghNootan/TypescriptCRUDProject#5]
Why are you setting the 204 manually?  

deleteArticle(articleId: string) {
      this.preProcessConfigurations();
      this.articleService.deleteArticleById(articleId)
	      .subscribe(successCode => {
		            //this.statusCode = successCode;
					//Expecting success code 204 from server
					this.statusCode = 204;
				    this.getAllArticles();	
				    this.backToCreateArticle();
			    },
		        errorCode => this.statusCode = errorCode);    
   }

**Comment by SinghNootan** [comment]
Hi Nathan,

We are setting 204 status manually because we have handled this status code in HTML page to show message like "Article deleted successfully.". We can not receive this status code from API as HTTP status code because  204 status is for "No content for request" and we have already handled 200 status with update that's why we have not used same.
